PATCH http://localhost:3000/posts
Content-Type: application/json

{
    "id": 10,
    "title": "Updated tags for post, added TypeScript",
    "postType": "story",
    "status": "draft",
    "content": "updated conten, along with tags",
    "tags": [1, 3, 4]
}